### ISSUE TITLE
Weird failure! msg issue

### ISSUE THREAD

**Issue by khem88** [tallygo/TallyGoAndroid#1]
When to press "start tallygo  NavFragment" button  nothing to happen just show a msg "Weird failure".

thanks

**Comment by haydenkaizeta** [comment]
@khem88 Hey, did you make sure to set your access token in the strings.xml? If so would you mind debugging what exception is thrown that causes that error message?

**Comment by khem88** [comment]
Thanks for reply.
                         yes I have add the access token in the string.xml and access with MetaData.
 It throw below exception
 E/com.tallygo.tallygoandroid.sdk.TallyGo: Must make call to TallyGo.initialize() before you can use TallyGo

com.tallygo.tallygoimplementation_navfragment E/Volley: [15202] BasicNetwork.performRequest: Unexpected response code 449 for https://api.tallygo.com/v1/route?time=2017-11-13T10:12:21Z&requestType=DepartureTime&coords=30.6981007,76.8538196;30.64255,76.817336;

**Comment by haydenkaizeta** [comment]
449 is an error caused by requesting use outside of our supported network. Building better error handling for this case.
