### ISSUE TITLE
Incorrect routing.

### ISSUE THREAD

**Issue by alexdevgit** [tallygo/TallyGoAndroid#10]
Hi team.
I noticed a wrong routing to a specific address.

Start point : can try from anywhere

Destination point: 2196 SHY BEAR WAY NW (latitude : 47.53150387, longitude : -122.0722261)

![img_0043 2](https://user-images.githubusercontent.com/17258541/40139446-e49631d4-591d-11e8-9f4c-1d8ab9464ee7.PNG)

Expected route should be to the red sign. Any ideas on what could be happening? Thanks in advance.

**Comment by mtriplett** [comment]
Hi Alex, we've identified the issue (the road in question didn't make it into the graph) and are working on a solution. Timing is TBD, but we're hoping to get it taken care of in the next 1-2 sprints. I'll post here when the fix is live.

**Comment by mtriplett** [comment]
Hey Alex, this issue should now be resolved as well. Take a look and let me know if you have any other problems.
