### ISSUE TITLE
App crashes when trying to route some distances (randomly)

### ISSUE THREAD

**Issue by alexdevgit** [tallygo/TallyGoAndroid#11]
Hi team.
When trying to load the route on turn by turn activity (random locations), app crashes and i am getting this error on log:
"Location update received after client was disconnected. Did you forget to unregister location updates before disconnecting?"
This locations for example:
init: LatLng [latitude=46.0493213, longitude=-117.3923985, altitude=0.0]
dest: LatLng [latitude=47.508584879, longitude=-122.52088254, altitude=0.0]

Any ideas on what could be happening? Thanks in advance.

**Comment by mtriplett** [comment]
This is a known issue and we're working to resolve it. ETA next build, stay tuned.

**Comment by mtriplett** [comment]
Hey Alex, this issue should now be resolved. Take a look and let me know if you have any other problems.
