### ISSUE TITLE
Error when setting up

### ISSUE THREAD

**Issue by LorenceHernandez** [tallygo/TallyGoAndroid#12]
https://pastebin.com/CVxbjBHp

This is where the error comes in:  TallyGo.getInstance(this).enableSimulation(true, false, currentLocation);

Can you help me for this one? I tried to follow the demo video.

**Comment by armond-avanes** [comment]
You need to set a "label" for your "<application>" tag in AndroidManifest.xml.

**Comment by LorenceHernandez** [comment]
@armond1978 thanks. fixed. is TallyGo can only be used for simulation?
