### ISSUE TITLE
Unable to run sample project

### ISSUE THREAD

**Issue by rlaguilar** [tallygo/TallyGoAndroid#2]
I'm getting the following error while trying to run the `TallyGoImplementation_Basic` sample proyect: 

> Error:Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.tallygo:tallygo-android:1.1.84.

**Comment by rlaguilar** [comment]
This seems to be a problem related with bintray. If a try to enter the url https://tallygo.bintray.com/TallyGoAndroid/com/tallygo/tallygo-android/1.2.97/tallygo-android-1.2.97.pom I get a Forbidden response.

**Comment by haydenkaizeta** [comment]
Fixed bintray distribution
