### ISSUE TITLE
Can I update mapbox without updating the tallygo

### ISSUE THREAD

**Issue by pepOSgh** [tallygo/TallyGoAndroid#5]
I'm currently using  the version **1.2.96**  of the tallygo sdk. This version uses the  version **5.1.4** of the mapbox sdk for android.

**Question**
Can I update the mapbox version without updating the tallygo version?

thanks

**Comment by haydenkaizeta** [comment]
Hey @pepOSgh,

While we try to keep the Mapbox SDK up to date, we have found their recent versions have regressions that are unfavorable. If you would like to specify your own version of the Mapbox SDK (that will also be used inside of our SDK) you may do the following:

```
    implementation('com.tallygo:tallygo-android:1.2.96@aar') {
        transitive = true
        exclude group: 'com.mapbox.mapboxsdk', module: 'mapbox-android-sdk'
    }
```

and then include the version you would like to use:

```
    implementation('com.mapbox.mapboxsdk:mapbox-android-sdk:5.1.4@aar') {
        transitive = true
    }
```

**Comment by pepOSgh** [comment]
thanks, @haydenkaizeta
