### ISSUE TITLE
Turn by Turn times out.

### ISSUE THREAD

**Issue by alexdevgit** [tallygo/TallyGoAndroid#7]
Looks like when distance is very far (from NYC to Kitsap for example) i get a time out error when computing the route.

**Comment by mtriplett** [comment]
We're looking into this issue and have verified the problem. Stay tuned for a resolution.

**Comment by briandilley** [comment]
Any update on this?

**Comment by mtriplett** [comment]
Yep, a fix is coming any day now. Stay tuned...

**Comment by mtriplett** [comment]
We’ve just deployed a fix that should resolve this issue. Let me know if you have any more trouble.

**Comment by alexdevgit** [comment]
Mat, thanks again for your time. I tried with same distance (NY to Kitsap) and app freezes (completely blocked). Do i also need to update my SDK?

**Comment by mtriplett** [comment]
Looks like this is a separate bug specifically with the Android SDK freezing — sorry for the confusion. The routing issue is resolved and this Android issue is also resolved, but not yet released. A new Android release will go out early/mid next week. Stay tuned — I’ll update here.

**Comment by mtriplett** [comment]
This issue should be resolved with SDK v2.0. Let me know if you run into any other issues.
