### ISSUE TITLE
v2.0.1 - App freezes sometimes loading turn by turn

### ISSUE THREAD

**Issue by alexdevgit** [tallygo/TallyGoAndroid#8]
Hi there team.
I updated to latest version (2.0.1) and i am steel getting the app freezed sometimes when loading the turn by turn. I also get stock sometimes on the turn by turn activity map when i get an "Error routing" toast message, without ability to get back to my main activity. I get "Unexpected response code 449.." error on the log.
I started testing on my own app an got this errors, then i downloaded your implementation sample project and still, same behavior. Any ideas on what could be happening? Thanks in advance

**Comment by haydenkaizeta** [comment]
@alexdevgit  We have a ticket to handle this more gracefully, however, the `449 error code` is caused by the SDK being used outside of our road network. Check out our guide to simulating your current location here: https://tallygo.com/docs/android/driving-simulator

**Comment by alexdevgit** [comment]
haydenkaizeta thanks for the fast response! I have had that error (449) placing both points inside US. Is all US inside TallyGo's road network or are there some areas missing?

**Comment by haydenkaizeta** [comment]
@alexdevgit We will soon add better handling of these error codes however it is possible to receive this error if your start or end points are too far from our road network (if you are more than 500m or so in most cases) so try keeping the points close to roads.

**Comment by mtriplett** [comment]
@alexdevgit Can you tell us what coordinates you're trying for your route?
