### ISSUE TITLE
Search bounds not available on v2.0.1 of SDK

### ISSUE THREAD

**Issue by alexdevgit** [tallygo/TallyGoAndroid#9]
Hi team.
I am not able to use the search bounds as i was doing on previous version of the SDK. Could that feature be included again? Is there another way to achieve this? Thanks in advance.

**Comment by haydenkaizeta** [comment]
@alexdevgit hey,
We have plans to release the search bounds as part of the SDK, we will update here when it is available.

**Comment by mtriplett** [comment]
Hey Alex, as of `2.0.8` this should now be possible. Take a look and let us know if you have any questions.
